// <auto-generated />
using System;
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211223181827_V3")]
    partial class V3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("Api.Domain.Entities.Cep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CEP")
                        .HasColumnType("varchar(10)");

                    b.Property<Guid>("CityId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Number")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("PublicPlace")
                        .HasColumnType("varchar(60)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CEP");

                    b.HasIndex("CityId");

                    b.ToTable("Ceps");
                });

            modelBuilder.Entity("Api.Domain.Entities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IbgeCode")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(45)");

                    b.Property<Guid>("StateId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("IbgeCode");

                    b.HasIndex("StateId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Api.Domain.Entities.State", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("UF")
                        .HasColumnType("char(2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("UF")
                        .IsUnique();

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            Id = new Guid("26bf4fac-6b74-460e-bc35-369fb85fe377"),
                            CreatedAt = new DateTime(2021, 12, 23, 18, 18, 26, 127, DateTimeKind.Utc).AddTicks(7865),
                            Name = "Acre",
                            UF = "AC"
                        },
                        new
                        {
                            Id = new Guid("bb34110c-1bb0-4d57-8fa6-a47791f8d53d"),
                            CreatedAt = new DateTime(2021, 12, 23, 18, 18, 26, 127, DateTimeKind.Utc).AddTicks(9866),
                            Name = "Alagoas",
                            UF = "AL"
                        },
                        new
                        {
                            Id = new Guid("9b7d755c-4ddc-4a19-920f-9281a669f6b2"),
                            CreatedAt = new DateTime(2021, 12, 23, 18, 18, 26, 127, DateTimeKind.Utc).AddTicks(9873),
                            Name = "Amapá",
                            UF = "AP"
                        },
                        new
                        {
                            Id = new Guid("150fd692-63ad-4a2c-bfdd-43a7afdb2ebf"),
                            Name = "Amazonas",
                            UF = "AM"
                        },
                        new
                        {
                            Id = new Guid("292f77a4-29dc-4b17-8c5f-ced63b97f7af"),
                            CreatedAt = new DateTime(2021, 12, 23, 18, 18, 26, 127, DateTimeKind.Utc).AddTicks(9878),
                            Name = "Bahia",
                            UF = "BA"
                        },
                        new
                        {
                            Id = new Guid("2ee0a586-66d5-42e4-b476-b0deb61bc551"),
                            CreatedAt = new DateTime(2021, 12, 23, 18, 18, 26, 127, DateTimeKind.Utc).AddTicks(9903),
                            Name = "Ceará",
                            UF = "CE"
                        },
                        new
                        {
                            Id = new Guid("2b8e410c-794d-4dd7-8544-942d5bfd98aa"),
                            Name = "Distrito Federal",
                            UF = "DF"
                        },
                        new
                        {
                            Id = new Guid("29197f73-1055-47e9-b046-7e0d77fcb067"),
                            Name = "Espírito Santo",
                            UF = "ES"
                        },
                        new
                        {
                            Id = new Guid("365ec8d9-b410-41b4-9469-a327769c0306"),
                            CreatedAt = new DateTime(2021, 12, 23, 18, 18, 26, 127, DateTimeKind.Utc).AddTicks(9914),
                            Name = "Goiás",
                            UF = "GO"
                        },
                        new
                        {
                            Id = new Guid("f04c8df2-3b2b-4e2c-8f05-96790e90754e"),
                            CreatedAt = new DateTime(2021, 12, 23, 18, 18, 26, 127, DateTimeKind.Utc).AddTicks(9916),
                            Name = "Maranhão",
                            UF = "MA"
                        },
                        new
                        {
                            Id = new Guid("a87c1f9e-91d6-423f-97ea-4bcf8b9c2081"),
                            CreatedAt = new DateTime(2021, 12, 23, 18, 18, 26, 127, DateTimeKind.Utc).AddTicks(9919),
                            Name = "Mato Grosso",
                            UF = "MT"
                        },
                        new
                        {
                            Id = new Guid("62fbeef7-6abb-40a4-824f-d804c2f38af4"),
                            CreatedAt = new DateTime(2021, 12, 23, 18, 18, 26, 127, DateTimeKind.Utc).AddTicks(9921),
                            Name = "Mato Grosso do Sul",
                            UF = "MS"
                        },
                        new
                        {
                            Id = new Guid("350d3fa9-87f5-4235-9977-d93b55255817"),
                            CreatedAt = new DateTime(2021, 12, 23, 18, 18, 26, 127, DateTimeKind.Utc).AddTicks(9923),
                            Name = "Minas Gerais",
                            UF = "MG"
                        },
                        new
                        {
                            Id = new Guid("6bc32d62-69bd-4bb8-8ed1-e4e501cd286b"),
                            CreatedAt = new DateTime(2021, 12, 23, 18, 18, 26, 127, DateTimeKind.Utc).AddTicks(9930),
                            Name = "Pará",
                            UF = "PA"
                        },
                        new
                        {
                            Id = new Guid("cb940838-bd25-4fd9-9725-cc8dbee1b4d3"),
                            CreatedAt = new DateTime(2021, 12, 23, 18, 18, 26, 127, DateTimeKind.Utc).AddTicks(9933),
                            Name = "Paraíba",
                            UF = "PB"
                        },
                        new
                        {
                            Id = new Guid("0d40fab2-a84d-4c7b-af0d-277f6126231f"),
                            CreatedAt = new DateTime(2021, 12, 23, 18, 18, 26, 127, DateTimeKind.Utc).AddTicks(9936),
                            Name = "Paraná",
                            UF = "PR"
                        },
                        new
                        {
                            Id = new Guid("f28c3aef-c9fb-4ebd-893b-73465076bf6c"),
                            CreatedAt = new DateTime(2021, 12, 23, 18, 18, 26, 127, DateTimeKind.Utc).AddTicks(9938),
                            Name = "Pernambuco",
                            UF = "PE"
                        },
                        new
                        {
                            Id = new Guid("24887789-2e1f-4bbf-a7a0-7a89b4c3a375"),
                            CreatedAt = new DateTime(2021, 12, 23, 18, 18, 26, 127, DateTimeKind.Utc).AddTicks(9941),
                            Name = "Piauí",
                            UF = "PI"
                        },
                        new
                        {
                            Id = new Guid("76cff268-7cc8-4880-a68d-30b62a3d2078"),
                            CreatedAt = new DateTime(2021, 12, 23, 18, 18, 26, 127, DateTimeKind.Utc).AddTicks(9943),
                            Name = "Roraima",
                            UF = "RR"
                        },
                        new
                        {
                            Id = new Guid("37976964-35a8-402a-99f8-722ec20f02e4"),
                            CreatedAt = new DateTime(2021, 12, 23, 18, 18, 26, 127, DateTimeKind.Utc).AddTicks(9946),
                            Name = "Rondônia",
                            UF = "RO"
                        },
                        new
                        {
                            Id = new Guid("1c5d6cc4-238f-4ec4-92a9-7a8527ed748c"),
                            CreatedAt = new DateTime(2021, 12, 23, 18, 18, 26, 127, DateTimeKind.Utc).AddTicks(9948),
                            Name = "Rio de Janeiro",
                            UF = "RJ"
                        },
                        new
                        {
                            Id = new Guid("568ae91a-b32c-4e7c-b73f-5ced9a45f57d"),
                            CreatedAt = new DateTime(2021, 12, 23, 18, 18, 26, 127, DateTimeKind.Utc).AddTicks(9956),
                            Name = "Rio Grande do Norte",
                            UF = "RN"
                        },
                        new
                        {
                            Id = new Guid("fb452cc9-e353-40a8-a665-d7068b850368"),
                            CreatedAt = new DateTime(2021, 12, 23, 18, 18, 26, 127, DateTimeKind.Utc).AddTicks(9958),
                            Name = "Rio Grande do Sul",
                            UF = "RS"
                        },
                        new
                        {
                            Id = new Guid("f24fe1b9-e603-40b5-b2f9-8093573e7113"),
                            CreatedAt = new DateTime(2021, 12, 23, 18, 18, 26, 127, DateTimeKind.Utc).AddTicks(9961),
                            Name = "Santa Catarina",
                            UF = "SC"
                        },
                        new
                        {
                            Id = new Guid("5daf0fe5-8f3c-4154-9a02-4461b24ef4b4"),
                            CreatedAt = new DateTime(2021, 12, 23, 18, 18, 26, 127, DateTimeKind.Utc).AddTicks(9963),
                            Name = "São Paulo",
                            UF = "SP"
                        },
                        new
                        {
                            Id = new Guid("0d71963e-293a-4404-be05-b6885762741c"),
                            CreatedAt = new DateTime(2021, 12, 23, 18, 18, 26, 127, DateTimeKind.Utc).AddTicks(9965),
                            Name = "Sergipe",
                            UF = "SE"
                        },
                        new
                        {
                            Id = new Guid("d8ab2dc4-51e0-4e2a-9f5a-98ef2056d207"),
                            CreatedAt = new DateTime(2021, 12, 23, 18, 18, 26, 127, DateTimeKind.Utc).AddTicks(9970),
                            Name = "Tocantins",
                            UF = "TO"
                        });
                });

            modelBuilder.Entity("Api.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Name")
                        .HasColumnType("VARCHAR(60)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("longblob");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Api.Domain.Entities.Cep", b =>
                {
                    b.HasOne("Api.Domain.Entities.City", "City")
                        .WithMany("Ceps")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Api.Domain.Entities.City", b =>
                {
                    b.HasOne("Api.Domain.Entities.State", "State")
                        .WithMany("Cities")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("Api.Domain.Entities.City", b =>
                {
                    b.Navigation("Ceps");
                });

            modelBuilder.Entity("Api.Domain.Entities.State", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
